### ISSUE TITLE
API connection is closed without response

### ISSUE THREAD

**Issue by GSI** [icecondor/web#7]
Hi Don,

Trying some basic calls from a python2 console:

<pre>
>>> import websocket, ssl, json                                                                                         [0/1611]
>>> ws = websocket.create_connection("wss://api.icecondor.com/v2",sslopt={"cert_reqs": ssl.CERT_NONE})
>>> print "'%s'" % ws.recv()
'{"id":"e098e6a9","method":"hello","params":{"name":"icecondor-api-nyc3-aa","version":"2-0317ba0"}}
'
>>> ws.send(json.dumps({"id":"e098e6a9","method":"auth.email","payload":{"email":"foo@example.org", "device_id":"foo"}}))
 
116
>>> print "'%s'" % ws.recv()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_core.py", line 348, in recv
    opcode, data = self.recv_data()
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_core.py", line 365, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_core.py", line 378, in recv_data_frame
    frame = self.recv_frame()
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_core.py", line 410, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_abnf.py", line 300, in recv_frame
    self.recv_header()
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_abnf.py", line 249, in recv_header
    header = self.recv_strict(2)
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_abnf.py", line 334, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_core.py", line 476, in _recv
    return recv(self.sock, bufsize)
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_socket.py", line 89, in recv
    raise WebSocketConnectionClosedException("Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
</pre>

Note that there's a looong delay upon calling `ws.recv()`.

Is there something wrong with the code or with the server end?

**Comment by donpdonp** [comment]
Hi - the simplest way to auth to the service is to watch the js console from icecondor.com. you'll see a message like

```json
{"id":"flikw","method":"auth.session","params":{"device_key":"browser_key-2f6c3ed4-b7ff-49d8-xxxx-xxxxx"}}
```

send that to the server.

**Comment by GSI** [comment]
Hmm, I suppose I should be able ot `location.create` right after authentication?

<pre>
>>> ws = websocket.create_connection("wss://api.icecondor.com/v2",sslopt={"cert_reqs": ssl.CERT_NONE}) ; print "'%s'" % ws.recv()
'{"id":"474efc25","method":"hello","params":{"name":"icecondor-api-nyc3-aa","version":"2-0317ba0"}}
'
>>> ws.send(json.dumps({"id":"1111","method":"auth.session","params":{"device_key":"browser_key-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"}})) ; print "'%s'" % ws.recv()
124
'{"id":"1111","result":{"user":{"id":"YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY"}}}
'
>>> ws.send(json.dumps({"id":"1111","method":"auth.session","params":{"device_key":"browser_key-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"}})) ; print "'%s'" % ws.recv()
124
'{"id":"1111","error":{"code":"AF1","message":"already authenticated","user_id":"YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY"}}
'
>>> ws.send(json.dumps({"id":"70306f5","method":"location.create","params":{"position": {"latitude":-30,"longitude":-50,}, "provider":"gps"}})) ; print "'%s'" % ws.recv()
138
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_core.py", line 348, in recv
    opcode, data = self.recv_data()
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_core.py", line 365, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_core.py", line 378, in recv_data_frame
    frame = self.recv_frame()
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_core.py", line 410, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_abnf.py", line 300, in recv_frame
    self.recv_header()
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_abnf.py", line 249, in recv_header
    header = self.recv_strict(2)
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_abnf.py", line 334, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_core.py", line 476, in _recv
    return recv(self.sock, bufsize)
  File "/home/g/.local/lib/python2.7/site-packages/websocket/_socket.py", line 89, in recv
    raise WebSocketConnectionClosedException("Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
</pre>

IceCondor.com confirms that I am *"already authenticated"*, but then `location.create` still causes the same error as before.

**Comment by GSI** [comment]
Just to be sure: Is the API v2 doc in the wiki correct?

I notice quite some differences to v1.

**Comment by donpdonp** [comment]
Hi, v2 is whats running now yes. sorry its not as well written as it could be. api.js is the actual server so if you want to dive into something, you can review the code there.

location.write is actually another level of access that is given only to android app auth tokens. the phone has half a key and the api has the other half (delivered in email). the keys are combined and then used by the phone app to authenticate. its not documented because i always intended to rework how tokens are done :).

every other action is available to you via the browser token.

**Comment by GSI** [comment]
So recording a location is "impossible" outside of android for the time being?

Or would it be reasonable to somehow work around that restriction?

**Comment by donpdonp** [comment]
the only way to record a location is to go through the undocumented auth steps that the mobile app does. all the code is here in github but it would take some work to figure out and implement in python.
